name: 'dhis2: verify (commits)'

on:
    pull_request:
        types: ['opened', 'edited', 'reopened', 'synchronize']

jobs:
    reusable_verify_commit_workflow_job:
        runs-on: ubuntu-latest
        steps:
        - uses: dhis2/gh-workflows/.github/workflows/dhis2-verify-commits@main