name: 'dhis2: e2e tests trigger from label'

on:
    pull_request:
        types: [labeled]

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
          - run: echo "$GITHUB_CONTEXT"
            env:
              GITHUB_CONTEXT: ${{ toJSON(github) }}

    dispatch-e2e-tests:
        if: github.event.label.name == 'e2e-tests'
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: dispatch
              run: gh workflow run e2e-tests-new.yml --ref $REF
              env:
                REF: ${{ github.head_ref }}
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}