name: "e2e tests"

# Requirements:
#
# - Secrets:
#     GITHUB_TOKEN
#     CYPRESS_DHIS2_USERNAME
#     CYPRESS_DHIS2_PASSWORD
#
# - Customize environment variables:
#     DHIS2_URL_PREFIX: Set the prefix for your instances. All instances are required to have this prefix followed by "dev" for the dev instance and "[majorVersion].[minorVersion]" for released versions (e.g. 2.39)
#
# - Optional customizations:
#     matrix containers:  Set the number of parallel Cypress instances running for each backend version
#     trigger labels: Set the labels that will trigger the workflow
#
# Usage:
#   

on:
  pull_request:
    types: [ labeled ]

env:
  DHIS2_URL_PREFIX: https://test.e2e.dhis2.org/ca-test-
  MATRIX_CONTAINERS: '[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]'


jobs:
  get-versions:
    runs-on: ubuntu-latest
    if: github.event.label.name == 'e2e-tests' || github.event.label.name == 'testing'
    outputs:
      versions: ${{ steps.released-versions.outputs.versions }}
    steps:
      - uses: actions/checkout@v2

      - uses: JoakimSM/action-instance-version@main
        id: instance-version
        with:
          instance-url: ${{env.DHIS2_URL_PREFIX}}dev
          username: ${{ secrets.CYPRESS_DHIS2_USERNAME }}
          password: ${{ secrets.CYPRESS_DHIS2_PASSWORD }}

      - uses: JoakimSM/action-applicable-released-versions@main
        id: released-versions
        with:
          dev-version: ${{ steps.instance-version.outputs.version }}

  compute-matrix-containers:
    runs-on: ubuntu-latest
    if: github.event.label.name == 'e2e-tests' || github.event.label.name == 'testing'
    outputs:
      containers: ${{ steps.compute.outputs.CCB}}
    steps:
      - run: echo "::set-output name=CCB::[1,2]"
        id: compute
        
  cypress:
    runs-on: ubuntu-latest
    needs: [get-versions, compute-matrix-containers]
    container: cypress/browsers:node14.7.0-chrome84
    strategy:
      # when one test fails, DO NOT cancel the other
      # containers, because this will kill Cypress processes
      # leaving the Dashboard hanging ...
      # https://github.com/cypress-io/github-action/issues/48
      fail-fast: false
      matrix:
        versions: ${{ fromJSON(needs.get-versions.outputs.versions) }}
        containers: ${{ fromJSON(needs.compute-matrix-containers.outputs.containers) }}
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}

      - name: Install
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          record: true
          parallel: true
          group: e2e-chrome-parallel-${{matrix.versions}}
          browser: chrome
          start: 'yarn start:forCypress'
          wait-on: 'http://localhost:3000'
          # wait for 200 secs for the server to respond
          wait-on-timeout: 200
        env:
          CI: true
          CYPRESS_RECORD_KEY: '6b0bce0d-a4e8-417b-bbee-9157cbe9a999'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CYPRESS_dhis2BaseUrl: ${{env.DHIS2_URL_PREFIX}}${{matrix.versions}}
          CYPRESS_dhis2InstanceVersion: ${{matrix.versions}}
          CYPRESS_dhis2Username: ${{secrets.CYPRESS_DHIS2_USERNAME}}
          CYPRESS_dhis2Password: ${{secrets.CYPRESS_DHIS2_PASSWORD}}

  call-e2e-tests-result:
    needs: cypress
    uses: ./.github/workflows/e2e-tests-result.yml
    with:
      result: true
